services:
  #MongoDB services
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  #node api
  api:
    container_name : node_api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo_db

volumes:
  mongo_db : {}
         


    


